### ISSUE TITLE
关于stack换源的问题

### ISSUE THREAD

**Issue by OkitaSan** [HaskellCNOrg/haskellcn#171]
我按照<a href=https://docs.haskellstack.org/en/stable/install_and_upgrade/#china-based-users>官网的指导</a>来配置并且替换了stack中的`config.yaml`的内容了stack,结果敲了`stack setup`以后一直报错如下：
```
Exception while reading snapshot from lts-16.8:
HttpExceptionRequest Request {
  host                 = "raw.githubusercontent.com"
  port                 = 443
  secure               = True
  requestHeaders       = [("User-Agent","Haskell pantry package")]
  path                 = "/commercialhaskell/stackage-snapshots/master/lts/16/8.yaml"
  queryString          = ""
  method               = "GET"
  proxy                = Nothing
  rawBody              = False
  redirectCount        = 10
  responseTimeout      = ResponseTimeoutDefault
  requestVersion       = HTTP/1.1
}
 (ConnectionFailure user error (Network.Socket.gai_strerror not supported: 11004))
```
请问如何解决

**Comment by leihao0401** [comment]
host                 = "raw.githubusercontent.com"
raw.githubusercontent.com这个网址，国内是访问不了的。

**Comment by freizl** [comment]
🤦 🤦

**Comment by SnowOnion** [comment]
墙的问题。
如果已经安装了 stack，可以同时使用 TUNA 的 Stackage 源 + Hackage 源来解决。

https://mirrors.tuna.tsinghua.edu.cn/help/hackage/

**Comment by SnowOnion** [comment]
这个 repo 貌似主要是旧论坛的内容 dump。
要用中文交流 Haskell 推荐在 https://zhihu.com 相关话题提问或 QQ 群 72874436

**Comment by SnowOnion** [comment]
哇，我刚注意到题主给的是 stack 链接的 China-based users 章节

**Comment by TENX-S** [comment]
Here 👋 我也一样，不过我挂了全局代理，依然有问题。

我配置了TUNA的stackage和hackage。
@SnowOnion 
> 墙的问题。
> 如果已经安装了 Haskell stack，可以同时使用 TUNA 的 Stackage 源 + Hackage 源来解决。（我记得 2019 年时安装 Haskell stack 本身也需要翻墙，而且无法改源解决；现在也许不需要了）
> https://mirrors.tuna.tsinghua.edu.cn/help/stackage/
> https://mirrors.tuna.tsinghua.edu.cn/help/hackage/
> @OkitaSan @leihao0401 @freizl

这是我的`~/.stack/config.yaml`
```yaml
package-indices:
  - download-prefix: http://mirrors.tuna.tsinghua.edu.cn/hackage/
    hackage-security:
        keyids:
        - 0a5c7ea47cd1b15f01f5f51a33adda7e655bc0f0b0615baa8e271f4c3351e21d
        - 1ea9ba32c526d1cc91ab5e5bd364ec5e9e8cb67179a471872f6e26f0ae773d42
        - 280b10153a522681163658cb49f632cde3f38d768b736ddbc901d99a1a772833
        - 2a96b1889dc221c17296fcc2bb34b908ca9734376f0f361660200935916ef201
        - 2c6c3627bd6c982990239487f1abd02e08a02e6cf16edb105a8012d444d870c3
        - 51f0161b906011b52c6613376b1ae937670da69322113a246a09f807c62f6921
        - 772e9f4c7db33d251d5c6e357199c819e569d130857dc225549b40845ff0890d
        - aa315286e6ad281ad61182235533c41e806e5a787e0b6d1e7eef3f09d137d2e9
        - fe331502606802feac15e514d9b9ea83fee8b6ffef71335479a2e68d84adc6b0
        key-threshold: 3 # number of keys required

        # ignore expiration date, see https://github.com/commercialhaskell/stack/pull/4614
        ignore-expiry: no

        
setup-info-locations: ["http://mirrors.tuna.tsinghua.edu.cn/stackage/stack-setup.yaml"]
urls:
  latest-snapshot: http://mirrors.tuna.tsinghua.edu.cn/stackage/snapshots.json
```

报错信息：
```
Exception while reading snapshot from https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/16/20.yaml:
HttpExceptionRequest Request {
  host                 = "raw.githubusercontent.com"
  port                 = 443
  secure               = True
  requestHeaders       = [("User-Agent","Haskell pantry package")]
  path                 = "/commercialhaskell/stackage-snapshots/master/lts/16/20.yaml"
  queryString          = ""
  method               = "GET"
  proxy                = Nothing
  rawBody              = False
  redirectCount        = 10
  responseTimeout      = ResponseTimeoutDefault
  requestVersion       = HTTP/1.1
}
 (InternalException (HandshakeFailed (Error_Misc "Network.Socket.recvBuf: resource vanished (Connection reset by peer)")))
```
我的浏览器倒是能正常访问报错信息中提到的`https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/16/20.yaml`
